language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - npm install
  - bower install
  - node node_modules/protractor/bin/webdriver-manager update

script: grunt; grunt e2e;

env:
  global:
    - secure: KDmYWjzh8Q1aPHo2jDAF+HRiDrEEntFlNyRvxjlsBuczItUwFPuvCk7eOBcqq8OmMlP7aV5ThKkC0tJ2wAKztU/m4yTuO/JsaxrTlCu5P2QqCiBnYz1djnlTOZqXkrk0bFRHQmAYgwJQELMCw1+fNsdCvtubliLsDUmGWZ3EeYA=
    - secure: YcRLt0q3xbmgazPZOGms8Hz9IXj5OUt7P6rv4yxELgt5K5MBnSH+jMaJViCDX4bZhX92jl6yq8UPMSX0YEoQI7STdFMAyy1z/a/WG4QEN12MJYT34JNnTItNanoX7UZOD+m5/aNaQRGINw8VdwT/DJ40+tCKrinrqtUS+CKHkp8=

addons:
  sauce_connect: true